### ISSUE TITLE
Redesign main menu

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#1062]

**Comment by peterpolman** [comment]
@miesz-ko Can you provide your requirements if you have any?

**Comment by miesz-ko** [comment]
> @miesz-ko Can you provide your requirements if you have any?

The main goal is to separate the end user, token and customer funnels. I imagine the funnels going something like; 

End User
- join Discord for more info
- sign up
- start a quest

Token User
- read token info
- buy token
- lock

Customer
- see pricing/template
- hit create campaign
- configure and read more in docs.

Would it be simplified if we just keep pricing | use cases | token | discord | launch app and on app.thx.network add 'create campaign' (Zealy3 has this)
