### ISSUE TITLE
Remove Spotify integration and authentication

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#111]
As we failed to get API access for our Spotify integration our production account is still limited to 20 users. This is not really workable of course so we are forced to deprecate the feature. Lets remove:
- the reward configuration options
- the integration component in Dashboard
- the authentication method in Auth.
- the proxy endpoints in API

**Comment by ghost** [comment]
@peterpolman do you want also remove all spotify logic in all the repositories or do you prefer **only** to remove routes and fronted parts?

**Comment by peterpolman** [comment]
@valeriagrazzini 
> the authentication method in ~API~ Auth.

Remove all the Spotify related logic indeed
