### ISSUE TITLE
Content update front-page

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#1117]
Content (work in progress) https://docs.google.com/document/d/1kNPqb0X_qebyflO6tZ6YfVL-nNKZkMc66H6JR3Wy0xM/edit?usp=sharing

**Comment by peterpolman** [comment]
@miesz-ko Will you finish this this week?

**Comment by miesz-ko** [comment]
> @miesz-ko Will you finish this this week?

Updated content here! https://docs.google.com/document/d/1kNPqb0X_qebyflO6tZ6YfVL-nNKZkMc66H6JR3Wy0xM/edit
