### ISSUE TITLE
Redeem promotions with a payment request

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#117]
Currently there is a specific redeem flow for promotions. We need to deprecate this, remove the code and start using the payment gateway in the same way we use it for buying an NFT.

- [ ] Extend payment request create modal to support attaching a promotion Id
- [ ] Extend POST /payments controller to store the promotionId
- [ ] Extend payment request response to return the promotionId
- [ ] Extend payment request view to show the promotion (return data from payment controller because of authentication)
- [ ] After a succesful payment, show the promotion and a link to the overview in the wallet

**Comment by ghost** [comment]
opened 3 PRs:

- API
- DASHBOARD
- WALLET

another task is created to manage the payment request creation after a Promotion Creation
