### ISSUE TITLE
Error shows when editing NFT metadata

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#126]
This errors shows when opening the edit modal for metadata created by importing an image.

![Image](https://user-images.githubusercontent.com/2378695/191192861-5eeefa5e-734e-4247-bef4-497533f96cc0.png)

**Comment by peterpolman** [comment]
@valeriagrazzini This one seems to be related to what you are working on now. Maybe its easier to fix em both in your PR?

**Comment by ghost** [comment]
@peterpolman  this is fixed in the PR https://github.com/thxprotocol/dashboard/pull/118
