### ISSUE TITLE
Send reminder to wallet users that did not migrate their funds yet

### ISSUE THREAD

**Issue by ghost** [thxprotocol/monorepo-legacy#133]
Send reminder to wallet users that did not migrate their funds yet
    1. Create a weekly agenda job
    2. Query erc20token collection for sub to obtain tokens per user
    3. Per token check the balances for account.address
    4. If balance is > 0 add token to list
    5. Send reminder email to user that he needs to migrate tokens in the list

**Comment by peterpolman** [comment]
.Not going forward with this as the amount of relevant users is not large enough.
