### ISSUE TITLE
Add clients router and controllers

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#2]
API

- [x] Add GET /clients endpoint and list all clients for the poolId in the X-PoolId header of the request
- [x] Add a new `clients: string[]` property on the AssetPool model which should contain a list of client id's
- [x] Add POST /clients endpoints to create a client and add the clientId to the `pool.clients` list of the pool in the header
- [ ] Add `clients.test.ts` test suite and test endpoints

**Comment by GarfDev** [comment]
Cause Client is a Proxy so is better if we move test task to Auth service instead

**Comment by GarfDev** [comment]
@peterpolman  Closing this with https://github.com/thxprotocol/api/pull/355

**Comment by peterpolman** [comment]
> Cause Client is a Proxy so is better if we move test task to Auth service instead

@GarfDev Don't agree since the client logic in auth is part of oidc-provider, so we assume that part is covered with tests already.

In the API project we extend the client we fetch through the proxy with information from the db.clients collection. There is also logic for the router and various endpoints. This is what should be covered with tests.
