### ISSUE TITLE
As a dashboard user I want to see metrics in pool cards

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#320]
Dashboard
- [ ] Remove current erc20 and erc721 totals from BaseCardPool
- [ ] Provide a list of pool metrics in the card instead 
```
320 Points (sum of all point rewards)
7 NFT Perks (sum of all ERC721PerkPayment)
5 Coin Perks (sum of all ERC20PerkPayment)
```

**Comment by ghost** [comment]
continued on branch `origin/pool-title`
the metrics also provide some info that will be useful for the pool dashboard
