### ISSUE TITLE
As a user I want to upload my own QR logo

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#33]
convert image data to black and white

** Ignore this snippet for now** We will offer coloured images as a default to make life easier.

```javascript
const img = document.getElementById("eeveelutions");
const canvas = document.getElementById("canvas");
const ctx = canvas.getContext("2d");

img.onload = function () {
  img.crossOrigin = "anonymous";
  ctx.drawImage(img, 0, 0);
  const imgData = ctx.getImageData(0, 0, canvas.width, canvas.height);
  for (i = 0; i < imgData.data.length; i += 4) {
    let count = imgData.data[i] + imgData.data[i + 1] + imgData.data[i + 2];
    let colour = 0;
    if (count > 383) colour = 255;

    imgData.data[i] = colour;
    imgData.data[i + 1] = colour;
    imgData.data[i + 2] = colour;
    imgData.data[i + 3] = 255;
  }
  ctx.putImageData(imgData, 0, 0);
};
```

Dashboard:
- [ ] Fetch brand.logoSrc from API in Reward component
- [ ] If there is a logoSrc image available, display it on the QRcode
- [ ] If not, display the default (THX) logo image.

API:
- [ ] Extend the new job for QR code generation to include brand.logoSrc if available (and default if not)
- [ ] See comment over here: https://github.com/thxprotocol/api/pull/360/files#r924374171

**Comment by GarfDev** [comment]
closing this wih following PRs:
https://github.com/thxprotocol/dashboard/pull/87
https://github.com/thxprotocol/api/pull/366
