### ISSUE TITLE
Revive Discord bot

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#369]
We will assume Discord bot users will 
- have a THX account 
- have their Discord connected to their THX account

The goal is to provide a similar info as the widget, that means listing rewards, perks and an accounts owned tokens.

Requirements
- [x] Discord Bot app should be use an AccountProxy to request account details based on Discord ID
- [x] Discord Bot should be configured for a specific PoolId (same as widget)
- [ ] Discord Bot should be able to list rewards for PoolId `GET /v1/rewards` (public)
- [ ] Discord Bot should be able to list perks for PoolId `GET /v1/perks` (public)
- [ ] Discord Bot should be able to list accounts tokens (ERC20Token and ERC721Token) for PoolId `GET /v1/erc721/token`

Commands
```
!thx show points
!thx show rewards
!thx show perks
!thx show tokens
```

**Comment by peterpolman** [comment]
@GarfDev Wondering if the Discord bot could become part of the monorepo. The unmaintained code is over here: https://github.com/thxprotocol/discord-bot

**Comment by GarfDev** [comment]
@peterpolman It need a refactor to migrate into this one: https://discordjs.guide/creating-your-bot/slash-commands.html#before-you-continue

**Comment by peterpolman** [comment]
Hmm in that case I think it might better to start a new app inside the monorepo that will become responsible for this and is kept minimal in terms of complexity and code. 

Would you set up a new app in the monorepo called "discord-bot"? This is how I think we should let this new app access account information.
- [x] Configure nodejs app similar to API project and give it its own mongodb
- [x] Register a `client_credentidals` grant in auth with at least `accounts:read` scope (similar to "THX API" client in auth db)
- [x] Add `GET /accounts/discord/:discordId` controller in auth to allow for requesting account info based on discord id
- [x] In this controller query for an accounts wit the `req.params.discordId`
- [x] Let's store `discordId` as a property in the auth.accounts db collection for now after a successful SSO (GET /oidc/callback/discord)
- [x] discord bot app should have an AccountProxy that requests an access token with its `client_credentials` grant and calls the `GET /accounts/discord/:discordId` endpoint when a slash commend is invoked that requires account info
