### ISSUE TITLE
As a user I want to be able to create payment request for NFT metadata

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#40]
Dashboard (2)
 - [ ] Extend CreatePaymentRequest modal with SelectNFTMetadata dropdown (see CreateReward modal and re-use component)
 - [ ] Extend POST /payments payload with optional `payment.metadata` property containing the `metadataId`

API (6)
 - [ ] Validate optional metadataId in `POST /payments payload`
 - [ ] Query for ERC721Metadata based on `metadataId` and push `payment.accessToken` onto `ERC721Metadata.whitelistedAccessTokens`.
 - [ ] Extend `PaymentService.pay()` callback with query for `ERC721Metadata` based on `payment.accessToken`
 - [ ] If there is a result, mint a token for that metadata for `payment.sender`.
 - [ ] Create tests

Wallet: (1)
- [ ] If available, show `title` and `description` in initial screen of payment UI
- [ ] If available, show `attributes` in success screen of payment UI

**Comment by ghost** [comment]
Hi @peterpolman, I have some questions:

DASHBOARD
_Extend CreatePaymentRequest modal with SelectNFTMetadata dropdown (see CreateReward modal and re-use component)_
you mean: if the pool is a NFT pool, show the drop down to select the available Metadata in a tab like it is now in the reward creation? And what if we have 5000 metadata for that NFT?

API
_Query for ERC721Metadata based on metadataId and push payment.accessToken onto ERC721Metadata.whitelistedAccessTokens_
is whitelistedAccessTokens a new field in the db?

**Comment by peterpolman** [comment]
@valeriagrazzini 
> And what if we have 5000 metadata for that NFT?

I guess most applicable would be a "Search Dropdown" UI component with lazy loading for the items in the list. It's not required to make that part of the scope for now though! For now I propose to just load the first 100 metadata items and stop there. I will create a task for implementing that search component.

**Comment by peterpolman** [comment]
fyi: https://github.com/thxprotocol/monorepo/issues/86
