### ISSUE TITLE
Create SDK for authorization_code grant clients

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#42]
Package: @thxnetwork/sdk

Deps:
- oidc-client-ts
- @toruslabs/customauth 
- typescript
- since its a browser SDK use window.fetch for doing HTTP requests

```
const client = new THXClient("WAGIJWGW", "WAWAGW", "https://example.com");
await client.signin();
```

Interface:
```
class THXClient {
  constructor(
    clientId: string,
    clientSecret: string,
    url: string
  ) {

  }
  signin(); // Do the oidc popup signin, getPrivateKey()
  signout(); // 
  account.get();
  erc721.tokens.get(); 
}
```
- [ ] Create new repository "sdk" @peterpolman Create repo before 26th of July
- [ ] Class exposed by package is THXClient
- [ ] Introduce THXClient.signin()
- [ ] On `signin()` use Torus util to fetch private key based on retrieved auth response
https://github.com/thxprotocol/wallet/blob/develop/src/utils/torus.ts
- [ ] On `signout()` use the regular oidc-client-ts signoutRedirect() method
- [ ] On `account.get()` call the api `GET /accounts endpoint`
- [ ] On `erc721.tokens.list()` call the api `GET /erc721/tokens`
- [ ] On `erc721.tokens.get(id: string)` call the api `GET /erc721/tokens/:id`

**Comment by peterpolman** [comment]
@GarfDev You can use this repo:
https://github.com/thxprotocol/sdk

**Comment by GarfDev** [comment]
@peterpolman got it
