### ISSUE TITLE
Improve email templates

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#43]
- [ ] Use this layout template and only change colors https://github.com/leemunroe/responsive-html-email-template
- [ ] Apply layout for these emails:
- Signup confirmation template
- Password reset template
- Send login link template
- QR codes ready template (API)

**Comment by ghost** [comment]
@peterpolman : do you want me to maintain in the template the social networks links?

**Comment by peterpolman** [comment]
Nope
