### ISSUE TITLE
Research token gating Shopify store product offering

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#511]
Research and test available Shopify features/app for token gating of product offering in a Shopify store.

**Comment by peterpolman** [comment]
@valeriagrazzini Hey! How is this one progressing? Could you report your findings in this ticket? Then I can keep track of progress and insights automatically.

**Comment by ghost** [comment]
- **Shopthru**
it's a very powerful app that allow the user to configure campaigns directly through the Shopify admin. 
It is based on perks.
You can set the start and the duration of the campaign, which products are selected as a perk, and the conditions.
The conditions are based on the owing of one or more assets, or being on a whitelist of wallet addresses.


![Image](https://user-images.githubusercontent.com/35029260/226586944-2dc3584b-cf62-40b8-8409-3ff8782b1f1b.png)



![Image](https://user-images.githubusercontent.com/35029260/226587073-fe069be5-023d-4de3-b089-0c414d76fc44.png)

- **Manifold**
this app allows to create product discount campaigns based on owing a specific asset it works only with polygon, ethereum and goerly blockchains. 
The campaign configuration is done directly in the shopify admin, but for the layout it requires a manual configuration. It is all explained in the tutorial on youtube: [https://www.youtube.com/watch?v=ms_Io2KxqMk](https://www.youtube.com/watch?v=ms_Io2KxqMk)
Campaign-wise, it is more simple, even though when I try to configure my asset (THX Token on Polygon) I always get an error.

- Taco
This is an app that is very very similar to THX. Same features, same logic to import NFT collection, same point rewards strategy and soo on. The app it's not embedded in shopify. Everything is configurable in the dashboard [https://dashboard.taco.xyz/manage](https://dashboard.taco.xyz/manage)
It's not very clear though how to inject the widget in the shop.

![Image](https://user-images.githubusercontent.com/35029260/226595146-06891208-d6c0-4e28-981a-c385b21d5913.png)



![Image](https://user-images.githubusercontent.com/35029260/226595242-dd650102-7474-497c-a643-dbce1849ee5f.png)



![Image](https://user-images.githubusercontent.com/35029260/226595352-c0a5f58f-275a-4405-8c50-1dc6edd59752.png)


- Toki Loyalty + Rewards
This is another one very similar to THX. It has also its own blockchain and wallet specific features, like THX.
Regarding loyalties, the configuration must be done in the dashboard. The user can create assets (only NFTs) not import.
Then the activities, challenges and rules must be configured as well. 
Enabling the app on the shopify admin is possible to show up the widget in the shopify store. However, when I tried to configure a shopify activity on the dashboard, it didn't work, and I have no errors shown. :/

![Image](https://user-images.githubusercontent.com/35029260/226598497-a4187075-1f49-4d23-9d47-c4c2389500b8.png)

![Image](https://user-images.githubusercontent.com/35029260/226598453-8ef6c63f-3d58-4805-82d4-484d35c2c6fc.png)
