### ISSUE TITLE
As a dashboard user I want to share preview URLs with pool transfers

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#521]
API
- [x] Move pools router to before `checkJwt` middleware in router index
- [x] Add checkJwt middle for all existing routes in the pools router
- [x] Add new `GET /pools/:id/transfers/:uuid` controller without checkJwt middleware
- [ ] We assume that `uuid` together with expiry are secure enough

Dashboard
- [ ] Test with this review URL syntax: `https://localhost:8082/preview/:poolId?poolTransfer=:uuid`
- [ ] On the preview page read `$route.query.poolTransfer` and request `GET /pools/:poolId/transfers/:poolTransferUuid`
- [ ] Display the `poolTransfer.expiry` value on the page
- [ ] Create a button on the page that redirects to the pool transfer URL, eg: `https://localhost:8082/pools/:poolId/transfer/:poolTransferUuid`

**Comment by ghost** [comment]
@peterpolman , two point are not clear to me:
1) where do I take the poolTransfer uuid from when I create the button?
2) the page that points to https://localhost:8082/pools/:poolId/transfer/:poolTransferUuid
will be a new page that displays the poolTransfer.expiry?

**Comment by peterpolman** [comment]
> where do I take the poolTransfer uuid from when I create the button?

From the URL! See Dashoard task 1: https://localhost:8082/preview/:poolId?poolTransfer=:uuid

> the page that points to https://localhost:8082/pools/:poolId/transfer/:poolTransferUuid
will be a new page that displays the poolTransfer.expiry?

This already exists in the router! It is used for passing the `poolTransferUuid` in the ExtraQueryParams during the auth request when somebody visits the existing pool transfer URL (the URL is the syntax of a pool transfer URL as you can see on the pools overview page).
