### ISSUE TITLE
Support showing ERC20 image urls from quickswap list in UI

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#79]
API
- [ ] Extend ERC20 modal with logoImgUrl property
- [ ] Upon **import** (POST /erc20/token) of ERC20 find the logoImgUrl for the tokenAddress in the payload.
- [ ] Store the quickswap tokenlist image url for this object 

Dashboard
- [ ] Adjust UI (BaseIdenticon.vue) to fetch logoImgUrl from the database
- [ ] Display the default BaseIdenticon logo image url if none is available in the db for the ERC20
- [ ] Create migration to set correct logoImgUrl properties for existing quickswap list tokens in the erc20 collection

**Comment by ghost** [comment]
created branch: erc20-logoImgUrl
when I try to import a token from Polygon list I get this Error: 
Error caught: Network with chainId 137 is not available

**Comment by peterpolman** [comment]
@valeriagrazzini  If you do that locally without providing a value for POLYGON_RPC in your API's .env I guess it would throw this. Could that be the cause?

**Comment by ghost** [comment]
@peterpolman  the error is happening because these value are missing in the env and env.example

POLYGON_RELAYER
POLYGON_RELAYER_API_KEY
POLYGON_RELAYER_API_SECRET
