### ISSUE TITLE
Make account.email an optional field

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#8]
Auth
- [ ] Make account.email field on account edit page editable
- [ ] Extend AccountService to send a confirmation email if the email address has changed
- [ ] Change the `active` flag into `isEmailVerified` and make sure regular signup still works

Dashboard
- [ ] Show new `ModalRequestAccountEmailUpdate.vue` with big button "Go to account page"

API
- [ ] When emails are sent, make sure the account has an email address and early return if not

Optional
- [ ] Login with Twitter and see what email is added for the account int he auth db
- [ ] Remove that email and try to login with Twitter SSO again
- [ ] If nothing breaks, create migration to remove all autogenerated Twitter and Spotify emails from the account collection
```
@spotify.thx.network
@twitter.thx.network
```

**Comment by ghost** [comment]
created branch account-email-optional (in auth repo)

I have implemented those parts:

-  Make account.email field on account edit page editable
-  Extend AccountService to send a confirmation email if the email address has changed
-  Change the active flag into isEmailVerified and make sure regular signup still works


For the rest of the tasks we may discuss about some points. For example:

- if I go to the account page in the dashboard, I can modify the email (now it sends an email for the email verification). 
So why is necessary to create a new Modal in the Dashboard?

- how can I login with twitter or spotify ? I only see the Google Sign in in the login page

**Comment by peterpolman** [comment]
> if I go to the account page in the dashboard, I can modify the email (now it sends an email for the email verification).
So why is necessary to create a new Modal in the Dashboard?

The modal should be shown quite early in the app lifecycle because we want to force the user to "go to the account" page and provide its email address.

Also make sure to check for account.email in the the places where emails are sent in the API

**Comment by ghost** [comment]
@peterpolman about this part: 

_Login with Twitter and see what email is added for the account int he auth db
 Remove that email and try to login with Twitter SSO again
 If nothing breaks, create migration to remove all autogenerated Twitter and Spotify emails from the account collection_

If I remove the twitter email from the database when I login again a **new account is created** instead of using the existing one

**Comment by peterpolman** [comment]
@valeriagrazzini Hmm that makes sense but is a bit unfortunate. If I remember correctly currently the mail address is used as identifier for authentication. 

In case of Twitter SSO we should store the user id returned from twitter, store that on account level and query for that (instead of email) when authenticating.

This behavior should also be applied for Google SSO and we should actually deprecate Spotify SSO since we didnt manage to get production level client access there, so dont bother about that one.

**Comment by peterpolman** [comment]
I would add these field to the schema:
```
account.twitterId
```

The first part of the applicable (<twitterId>@twitter.thx.network) email addresses will contain the user ID's you need to store. So no need to call API's here.
