### ISSUE TITLE
Implement vue-select for Dropdown Search component

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#86]
- [ ] Get the package `vue-select`
- [ ] Make sure to adjust style classes to bootstrap dropdown style classes
- [ ] Implement for listing metadata
- [ ] Configure paging for large (50+) responses https://vue-select.org/guide/pagination.html

**Comment by ghost** [comment]
implemented dropdown pagination but without using the component vue-select.
The reason why: could not customize the items and also the navigation buttons were not very functional

**Comment by peterpolman** [comment]
@valeriagrazzini Did you look into this one? 
https://github.com/thxprotocol/auth/pull/110/files#r962612939

```html
<v-select :options="options" label="title">
  <template v-slot:option="option">
    <span :class="option.icon"></span>
    {{ option.title }}
  </template>
</v-select>
```

This template looks like it should do the trick. Ill have a look at your PR anyway though!
