### ISSUE TITLE
Expand test coverage

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#863]
# Test Suites

## Quests
- [ ] Create campaign
- [ ] Add quest (case per variant)
- [ ] Update quests for all types
- [ ] Delete quests for all types
## Rewards
- [ ] Create campaign
- [ ] Add reward (case per variant)
- [ ] Update quests for all types
- [ ] Delete quests for all types
## Integrations
- [ ] Create campaign
- [ ] Add Discord integration
- [ ] Change Discord config
- [ ] Add Twitter integration
- [ ] Change Twitter integration
## Settings
- [ ] Create campaign
- [ ] Change campaign settings
- [ ] Change widget personalisation
- [ ] Delete campaign
## Developer
- [ ] Create campaign
- [ ] Add API client
- [ ] Create Identity
- [ ] Register Event for Identity
## Quest entries
- [ ] Create campaign
- [ ] Create quest (case per variant)
- [ ] Complete quests for all types
- [ ] Verify point balance
- [ ] Verify quest locks
## Reward payments
- [ ] Create campaign
- [ ] Create rewards (case per variant)
- [ ] Purchase rewards for all types
- [ ] Verify quest locks
- [ ] Verify point balance
- [ ] List tokens and payments
## Token transfers
- [ ] Create tokens for user
- [ ] Transfer tokens 
- [ ] Verify balances
## QR Codes
- [ ] Create campaign
- [ ] Create NFT reward
- [ ] Create QR codes
- [ ] Claim QR code
- [ ] List tokens

**Comment by adrianthx** [comment]
@peterpolman From the above list, these are created. I will close this big ticket and create smaller ones for remaining areas, as discussed.

Campaign - Dashboard - https://test-management.browserstack.com/projects/159235/folder/3713405/test-cases 
Analytics - https://test-management.browserstack.com/projects/159235/folder/3713407/test-cases
Quests - Published - https://test-management.browserstack.com/projects/159235/folder/3713442/test-cases
Quests - Unpublished - https://test-management.browserstack.com/projects/159235/folder/3713463/test-cases
Rewards - Published - https://test-management.browserstack.com/projects/159235/folder/3713464/test-cases
Rewards - Unpublished - https://test-management.browserstack.com/projects/159235/folder/3713465/test-cases
Participants - https://test-management.browserstack.com/projects/159235/folder/3713411/test-cases
Integrations - https://test-management.browserstack.com/projects/159235/folder/3713412/test-cases

**Comment by adrianthx** [comment]
Remaining:

- Developer - https://github.com/orgs/thxprotocol/projects/3/views/80?pane=issue&itemId=62395603
- Campaign Settings - https://github.com/orgs/thxprotocol/projects/3/views/1?pane=issue&itemId=62396136
- Campaign Preview + Widget - https://github.com/orgs/thxprotocol/projects/3/views/80?pane=issue&itemId=62391265
- Coins - https://github.com/orgs/thxprotocol/projects/3/views/80?pane=issue&itemId=62396684
- NFT - https://github.com/orgs/thxprotocol/projects/3/views/80?pane=issue&itemId=62396836
- QR Codes - https://github.com/orgs/thxprotocol/projects/3/views/80?pane=issue&itemId=62396954
