### ISSUE TITLE
Add quest metadata for relevant types

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#908]

**Comment by Phlame68** [comment]
Love & gratitude

**Comment by Phlame68** [comment]
![CD052503-B396-4B6E-8387-90AFE6816E83](https://github.com/thxprotocol/monorepo/assets/164750952/48cdf5ab-0cc8-4de5-bf5c-c49eca2384db)

bc1qgtgxd3dlzvlwhqg23pv5cys4lepp3h5qgj8ku0
