### ISSUE TITLE
Previews of uploaded images not shown

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#92]
Dashboard - Theme section does not show preview images when they are uploaded. Also not after a refresh of the page.

**Comment by peterpolman** [comment]
@GarfDev I see this one is marked as done, but where can I find the PR with the changes? I expected one in API since you explained there was an issue with the env vars there.

**Comment by GarfDev** [comment]
@peterpolman I was DM you about this last night, this cause by environment variables name changed:
`AWS_ACCESS_KEY_ID` => `AWS_ACCESS_KEY`
`AWS_SECRET_ACCESS_KEY` => `AWS_SECRET_KEY`

Just rollback does env changes on deployments is okay I guess, cause in code, those value still required:
`AWS_ACCESS_KEY_ID`
`AWS_SECRET_ACCESS_KEY`
