### ISSUE TITLE
Move amplify apps into monorepo

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#94]
@GarfDev Found this one, could it be relevant for our amplify deployments? https://docs.aws.amazon.com/amplify/latest/userguide/monorepo-configuration.html

**Comment by GarfDev** [comment]
It relevant, but I will need AWS test environment and credential to test if it work for Nx

**Comment by peterpolman** [comment]
Alright, lemme see what I can do
