### ISSUE TITLE
Transfer feedback from doc to gh

### ISSUE THREAD

**Issue by adrianthx** [thxprotocol/monorepo-legacy#975]
After the discussion with Peter, we agreed to move all the feedback from the G-doc to gh and create individual tickets for each found issue. 

https://docs.google.com/document/d/1PhoiVPDbla3DRHl9YfIrdsye46TDBBMGNxYW_xD2rDY/edit

**Comment by peterpolman** [comment]
@adrianthx Can we close this one?
